// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


console.log("Hello, BuckleScript and Reason!");

console.log("this is reason CODE");

(( console.log('This middle javascript') ));

/*  Not a pure module */
